export {ActiveSlider} from './Sliders/activeSlider/ActiveSlider'
export { About} from './Sections/About/About'
export { Assortment} from './Sections/Assortment/Assortment'
export { Contact} from './Sections/Contact/Contact'
export { AutoSlider } from './Sliders/autoSlider/autoSlider'
export { Catalog} from './Catalog/Catalog'
export { CatalogCompany} from './CatalogCompany/CatalogCompany'
export { ProductSlider} from './Sliders/ProductSlider/ProductSlider'
export { FeedbackForm} from './FeedbackForm/FeedbackForm'
export { Menu} from './Blocks/Menu/Menu'
export {Loading} from './Blocks/Loading/Loading'
export { Modal} from './UI/Modal/Modal'
export { List} from './Blocks/List/List'
export { CatalogPreviewItem} from './Blocks/CatalogPreviewItem/CatalogPreviewItem'
export { CatalogItemCompany} from './Blocks/CatalogItemCompany/CatalogItemCompany'

export {AuthForm} from './Forms/AuthForm/AuthForm'
export {ChangePasswordFrom} from './Forms/ChangePasswordFrom/ChangePasswordFrom'
export {ForgotPasswordForm} from './Forms/ForgotPasswordForm/ForgotPasswordForm'

